app = "desafioarcano"
primary_region = "eze"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NODE_ENV = "production"
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  health_check_timeout = "60s"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2